//barrel.file
export * from "./ads/ads.component";
export * from "./index/index.component";
export * from "./users/users.component";
export * from "./userDetail/userDetail.component";
export * from './adsDetail/adsDetail.component';
export * from "./login/login.component";
export * from "./register/register.component";
export * from "./createAd/createAd.component";
export * from "./myAds/myAds.component";
export * from "./unauthorized/unauthorized.component";
export * from "./notfound/notfound.component";
export * from "./pages.module";
export * from "./pages.route";
export * from "./../models/user.model";
export * from "./../models/ads.model";
export * from "./../models/checkbox.model";
export * from "./../models/register.user.model";
export * from "./../models/token.model";